const bMenu = document.querySelectorAll("#b-menu")
const bPi = document.querySelector("#b-pi")
const bRoot = document.querySelector("#b-root")
const bTopower = document.querySelector("#b-topower")
const bClear = document.querySelector("#b-clear")
const bBrackets = document.querySelector("#b-ob #b-cb")
const bPercent = document.querySelector("#b-percent")
const bNumbers = document.querySelectorAll("#b-7, #b-8, #b-9 #b-4 #b-5 #b-6 #b-1 #b-2 #b-3 #b-0")
const bOperators = document.querySelector("#b-divide #b-times #b-minus #b-plus")
const bDot = document.querySelector("#b-dot")
const bDel = document.querySelector("#b-del")
const bEquals = document.querySelector("#b-equals")

bNumbers.forEach(bNumbers.addEventListener("click", ))

bMenu.addEventListener("click", menuBClick)
bPi.addEventListener("click", piBClick)
bRoot.addEventListener("click", rootBClick)
bTopower.addEventListener("click", topowerBClick)
bClear.addEventListener("click", clearBClick)
bOb.addEventListener("click", obBClick)
bOc.addEventListener("click", cbBClick)
bPercent.addEventListener("click", percentBClick)
bDivide.addEventListener("click", divideBClick)
b7.addEventListener("click", 7 BClick)
b8.addEventListener("click", 8 BClick)
b9.addEventListener("click", 9 BClick)
bTimes.addEventListener("click", timesBClick)
b4.addEventListener("click", 4 BClick)
b5.addEventListener("click", 5 BClick)
b6.addEventListener("click", 6 BClick)
bMinus.addEventListener("click", minusBClick)
b1.addEventListener("click", 1 BClick)
b2.addEventListener("click", 2 BClick)
b3.addEventListener("click", 3 BClick)
bPlus.addEventListener("click", plusBClick)
b0.addEventListener("click", 0B Click)
bDot.addEventListener("click", dotBClick)
bDel.addEventListener("click", delBClick)
bEquals.addEventListener("click", equalsBClick)


const 0B Click = (event) => {

}